from card import *

class Deck():
    def __init__(self):
        deck = [
            FoolishIndecisive,
            PoisonousMagician,
            LoneHighPriestess,
            CrushingEmperor,
            WiseHierophant,
            LoversBeneath,
            NobleChariot,
            StrengthAbove,
            ElusiveHermit,
            WheelOfFortune,
            JusticeOfNaught,
            HangedMansWoe,
            DeathLingerer,
            TemperanceTriad,
            DevilDeposit,
            TowerAbove,
            StarMellowLight,
            MoonlightEmbassy,
            SunOfSonglett,
            JudgementYou,
            WorldOfFinale,
            PageOfWandsAhold,
            PageOfLostSword,
            PageOfPentaclesGrace,
            ScorpioLethality,
            CapricornAssistance,
            PiscesPondLuck,
            AssuredCancer,
            SunsSteedLeo,
            VirgosHarvest,
            TaurusQuaker,
            GeminiPactsworns,
            BlazingAries,
            GrandLibra,
            BurstingAquarius,
            SagittariusHunter,
            WealthyRat,
            HonestPig,
            LoyalDog,
            TirelessRooster,
            CuriousMonkeys,
            DayOfSheep,
            MimicHorse,
            LaughingSnake,
            LuckyDragon,
            CalmRabbitFestival,
            UnmovingTigers,
            VictorysOx
        ]
        self.deck = deck